# Generated by Django 5.0.2 on 2024-04-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(default=20000, verbose_name='стоимость курса'),
        ),
    ]
